<a href="https://colab.research.google.com/github/ZoofishanChohan/NLP/blob/main/Text_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.layers import TextVectorization

In [11]:
# creating a data set
sentences = [

             "I love my dog and papi",
             "I love my cat and simba and chutki and buffy",
             "You love my dog and my cat",
             "Do you think my dog is amazing?"


]

In [4]:
MAX_VOCAB_SIZE = 20000

In [5]:
vectorization_layer = TextVectorization(max_tokens=MAX_VOCAB_SIZE,
                                         #output_mode="int",
                                         #output_sequence_length=10
                                        )

In [12]:
vectorization_layer.adapt(sentences)

In [13]:
sequences = vectorization_layer(sentences)

In [14]:
sequences

<tf.Tensor: shape=(4, 10), dtype=int64, numpy=
array([[ 7,  4,  2,  5,  3, 11,  0,  0,  0,  0],
       [ 7,  4,  2,  8,  3, 10,  3, 14,  3, 15],
       [ 6,  4,  2,  5,  3,  2,  8,  0,  0,  0],
       [13,  6,  9,  2,  5, 12, 16,  0,  0,  0]])>

In [15]:
vectorization_layer.get_vocabulary()

['',
 '[UNK]',
 np.str_('my'),
 np.str_('and'),
 np.str_('love'),
 np.str_('dog'),
 np.str_('you'),
 np.str_('i'),
 np.str_('cat'),
 np.str_('think'),
 np.str_('simba'),
 np.str_('papi'),
 np.str_('is'),
 np.str_('do'),
 np.str_('chutki'),
 np.str_('buffy'),
 np.str_('amazing')]

In [20]:
# word to index mapping
word2index = {}
for index, word in enumerate(vectorization_layer.get_vocabulary()):
    word2index[word] = index

print(word2index)

{'': 0, '[UNK]': 1, np.str_('my'): 2, np.str_('and'): 3, np.str_('love'): 4, np.str_('dog'): 5, np.str_('you'): 6, np.str_('i'): 7, np.str_('cat'): 8, np.str_('think'): 9, np.str_('simba'): 10, np.str_('papi'): 11, np.str_('is'): 12, np.str_('do'): 13, np.str_('chutki'): 14, np.str_('buffy'): 15, np.str_('amazing'): 16}


In [27]:
# truncation with output = 3
text_vectorization_layer_truncated = TextVectorization(max_tokens=MAX_VOCAB_SIZE,
                                         output_mode="int",
                                         output_sequence_length=3
                                        )
text_vectorization_layer_truncated.adapt(sentences)
sequences = text_vectorization_layer_truncated(sentences)

In [28]:
sequences

<tf.Tensor: shape=(4, 3), dtype=int64, numpy=
array([[ 7,  4,  2],
       [ 7,  4,  2],
       [ 6,  4,  2],
       [13,  6,  9]])>

In [31]:
# ragged output
vectorization_layer_ragged = TextVectorization(
                                         max_tokens=MAX_VOCAB_SIZE,
                                         ragged = True
                                        )
vectorization_layer_ragged.adapt(sentences)
sequences = vectorization_layer_ragged(sentences)

In [32]:
sequences

<tf.RaggedTensor [[7, 4, 2, 5, 3, 11], [7, 4, 2, 8, 3, 10, 3, 14, 3, 15],
 [6, 4, 2, 5, 3, 2, 8], [13, 6, 9, 2, 5, 12, 16]]>